version: 5.1.0
variant: default
logo:
  text: 大帝的博客
head:
  favicon: /img/favicon.svg
  manifest:
    name: 大帝的博客
    short_name: 大帝的博客
    start_url: https://blog.dadilive.top
    theme_color:
    background_color:
    display: standalone
    icons:
      - src: ""
        sizes: ""
        type:
  open_graph:
    title:
    type: blog
    url:
    image:
    site_name:
    author:
    description:
    twitter_card:
    twitter_id:
    twitter_site:
    google_plus:
    fb_admins:
    fb_app_id:
  structured_data:
    title:
    description:
    url:
    author:
    publisher:
    publisher_logo:
    image:
  meta:
    - ""
  rss:
navbar:
  menu:
    首页 : /
    分类 : /categories
    标签 : /tags
    归档 : /archives
    关于我 : /about-me
  # links:
  #     Download on GitHub:
  #         icon: fab fa-github
  #         url: https://github.com/ppoffice/hexo-theme-icarus
footer:
  links:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution 4.0 International:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    Download on GitHub:
      icon: fab fa-github
      url: https://github.com/ppoffice/hexo-theme-icarus
article:
  highlight:
    theme: atom-one-light
    clipboard: true
    fold: folded
  readtime: true
  update_time: true
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    Noncommercial:
      icon: fab fa-creative-commons-nc
      url: https://creativecommons.org/licenses/by-nc/4.0/
search:
  type: insight
  index_pages: true
# comment:
#     type: disqus
#     shortname: ''
donates:
  # -
  #     type: afdian
  #     url: ''
  - type: alipay
    qrcode: ""
  # -
  #     type: buymeacoffee
  #     url: ''
  # -
  #     type: patreon
  #     url: ''
  # -
  #     type: paypal
  #     business: ''
  #     currency_code: USD
  - type: wechat
    qrcode: ""
# share:
# type: sharethis
# install_url: ''
sidebar:
  left:
    sticky: false
  right:
    sticky: true
widgets:
  - position: left
    type: profile
    author: 大帝
    author_title: 一个软件工程师
    # location: Your location
    avatar: /images/avataaars.svg
    avatar_rounded: true
    gravatar:
    # follow_link: https://github.com/chenzd123456
    social_links:
      # Github: fab fa-github
      #     icon: fab fa-github
      #     url: https://github.com/chenzd123456
      # Facebook:
      #     icon: fab fa-facebook
      #     url: https://facebook.com
      # Twitter:
      #     icon: fab fa-twitter
      #     url: https://twitter.com
      # Dribbble:
      #     icon: fab fa-dribbble
      #     url: https://dribbble.com
      # RSS:
      #     icon: fas fa-rss
      #     url: /
  - position: left
    type: toc
    index: true
    collapsed: true
    depth: 3
  - position: left
    type: links
    links:
      大帝的网盘: "https://public.dadilive.top/"
  - position: left
    type: categories
  - position: left
    type: recent_posts
  - position: left
    type: archives
  - position: left
    type: tags
    order_by: name
    amount:
    show_count: true
  # -
  #     position: left
  #     type: subscribe_email
  #     description:
  #     feedburner_id: ''
  # -
  #     position: left
  #     type: adsense
  #     client_id: ''
  #     slot_id: ''
  # -
  #     position: left
  #     type: followit
  #     description:
  #     action_url: ''
  #     verification_code: ''
plugins:
  animejs: true
  back_to_top: true
  baidu_analytics:
    tracking_id:
  bing_webmaster:
    tracking_id:
  busuanzi: false
  cnzz:
    id:
    web_id:
  cookie_consent:
    type: info
    theme: edgeless
    static: false
    position: bottom
    policyLink: https://www.cookiesandyou.com/
  gallery: true
  google_analytics:
    tracking_id:
  hotjar:
    site_id:
  katex: false
  mathjax: false
  outdated_browser: false
  progressbar: true
  statcounter:
    project:
    security:
  twitter_conversion_tracking:
    pixel_id:
providers:
  cdn: loli
  fontcdn: loli
  iconcdn: loli
