title: Adam的博客
subtitle: Adam的博客
description: 本博客主要作用是记录自己折(muo)腾(yu)的各种技术，以上！
keywords: Adam的博客
author: chenzd123456@gmail.com
language: zh-CN
timezone: Asia/Shanghai
url: "https://blog.dadilive.top"
root: /
permalink: ":year:month:day/:abbrlink.html"
permalink_defaults: null
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks, dont be false, vercel will miss the page
  trailing_html: true # Set to false to remove trailing '.html' from permalinks, dont be false, vercel will miss the page
abbrlink:
  alg: crc32
  rep: hex
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ":lang"
skip_render:
  - "*.html"
new_post_name: ":title.md"
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: null
index_generator:
  path: ""
  per_page: 10
  order_by: "-date"
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: "HH:mm:ss"
per_page: 10
pagination_dir: page
theme: icarus
deploy:
  type: null
# 开启压缩
neat_enable: true
neat_html:
  enable: true
  exclude:
neat_css:
  enable: true
  exclude:
    - "**/*.min.css"
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - "**/*.min.js"
    - "**/index.js"
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
uglify:
  mangle: true
  output:
  compress:
  exclude:
    - "*.min.js"
clean_css:
  exclude:
    - "*.min.css"
html_minifier:
  collapseBooleanAttributes: true
  collapseWhitespace: true
  # ignoreCustomComments: [!!js/regexp /^\s*more/]
  removeComments: true
  removeEmptyAttributes: true
  removeScriptTypeAttributes: true
  removeStyleLinkTypeAttributes: true
  minifyJS: true
  minifyCSS: true
hexo_markmap:
  pjax: false
  katex: false
  prism: false
  CDN:
    d3_js: https://fastly.jsdelivr.net/npm/d3@6
    markmap_view_js: https://fastly.jsdelivr.net/npm/markmap-view@0.2.7
    katex_css: https://fastly.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css
    prism_css: https://fastly.jsdelivr.net/npm/prismjs@1.25.0/themes/prism.css
